version: '3.5'

services:
  php:
    container_name: php
    build: .
    volumes:
      - .:/app
    ports:
      - 8888:8000
    depends_on:
      - PostgreSQL

  PostgreSQL:
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=Vlad
    image: postgres:15.3-alpine

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      volumes:
        - .:/app
      environment:
        PGADMIN_DEFAULT_EMAIL: vlad28102020@gmail.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - 5050:80