version: '3'

services:
  php:
    build: ./PHP
    volumes:
      - ../public:/app/public
      - ../:/app
    working_dir: /app/public
    user: '1000:1000'
    ports:
      - 8000:8000
    command: bash -c "cd /app && composer install && php -S 0.0.0.0:8000 -t /app/public"